Blog/Models/Admin/Post/PostEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Ajax.Utilities;

namespace Blog.Models.Admin.Post
{
    public class PostEditModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Guid Author { get; set; }
        public string Timestamp { get; set; }
        public bool CommentsEnabled { get; set; }
        public string Status { get; set; }
        public string Visibility { get; set; }
        public Guid? FeaturedImage { get; set; }
        public string Slug { get; set; }
        public string AddOrEdit { get; set; }
        public List<string> PossibleStatuses { get; set; }
        public List<string> PossibleVisibilities { get; set; }


        public PostEditModel()
        {
            
        }

        public PostEditModel(Blog.Post post, string addOrEdit)
        {
            Id = post.Id;
            Title = post.Title;
            Body = post.Body;
            Author = post.Author;
            Timestamp = post.Timestamp.ToString();
            CommentsEnabled = post.CommentsEnabled;
            Status = post.Status;
            Visibility = post.Visibility;
            FeaturedImage = post.FeaturedImage;
            Slug = post.Slug;
            AddOrEdit = addOrEdit;

            List<string> possibleStatusesTemp = new List<string>();
            possibleStatusesTemp.Add("Draft");
            possibleStatusesTemp.Add("Pending Review");
            possibleStatusesTemp.Add("Published");
            PossibleStatuses = possibleStatusesTemp;

            List<string> possibleVisibilitiesTemp = new List<string>();
            possibleVisibilitiesTemp.Add("Public");
            possibleVisibilitiesTemp.Add("Public Stickied");
            possibleVisibilitiesTemp.Add("Password Protected");
            possibleVisibilitiesTemp.Add("Private");
            PossibleVisibilities = possibleVisibilitiesTemp;

        }

        public static PostEditModel PostEdit(string id)
        {
            BlogDataDataContext database = new BlogDataDataContext();

            if (id.IsNullOrWhiteSpace())
            {
                Blog.Post post = new Blog.Post();
                post.Timestamp = DateTime.Now;
                PostEditModel model = new PostEditModel(post, "Add");
                return model;
            }
            else
            {
                Blog.Post post = database.Posts.FirstOrDefault(x => x.Id == new Guid(id));
                PostEditModel model = new PostEditModel(post, "Edit");
                return model;
            }
        }

        public static bool DeletePost(string id)
        {
            BlogDataDataContext database = new BlogDataDataContext();

            var post = database.Posts.FirstOrDefault(x => x.Id == new Guid(id));
            var categoryMap = database.PostCategoryMaps.Where(x => x.PostId == post.Id);
            var tagMap = database.PostTagMaps.Where(x => x.PostId == post.Id);

            database.Posts.DeleteOnSubmit(post);
            database.PostCategoryMaps.DeleteAllOnSubmit(categoryMap);
            database.PostTagMaps.DeleteAllOnSubmit(tagMap);

            database.SubmitChanges();
            return true;
        }
        
        public static Blog.Post PostEditPost(PostEditModel model)
        {
            BlogDataDataContext database = new BlogDataDataContext();
            Blog.Post databaseModel = database.Posts.FirstOrDefault(x => x.Id == model.Id);

            if (databaseModel != null)
            {
                databaseModel.Title = model.Title;
                databaseModel.Body = model.Body;
                databaseModel.Author = new Guid("cebe8069-bd64-4dc9-8622-d3de189287b1"); // todo: get current user id
                databaseModel.Timestamp = Convert.ToDateTime(model.Timestamp);
                databaseModel.CommentsEnabled = model.CommentsEnabled;
                databaseModel.Status = model.Status;
                databaseModel.Visibility = model.Visibility;
                databaseModel.FeaturedImage = model.FeaturedImage;
                databaseModel.Slug = model.Slug;
            }
            else
            {
                databaseModel = new Blog.Post();

                databaseModel.Id = Guid.NewGuid();

                databaseModel.Title = model.Title;
                databaseModel.Body = model.Body;
                databaseModel.Author = new Guid("cebe8069-bd64-4dc9-8622-d3de189287b1"); // todo: get current user id
                databaseModel.Timestamp = Convert.ToDateTime(model.Timestamp);
                databaseModel.CommentsEnabled = model.CommentsEnabled;
                databaseModel.Status = model.Status;
                databaseModel.Visibility = model.Visibility;
                databaseModel.FeaturedImage = model.FeaturedImage;
                databaseModel.Slug = model.Slug;

                database.Posts.InsertOnSubmit(databaseModel);
            }
            database.SubmitChanges();

            return databaseModel;
        }
    }
}

Blog/Models/Admin/Post/PostIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Blog.Models.Admin.Post
{
    public class PostIndexTableRow
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Categories { get; set; }
        public string Tags { get; set; }
        public string Comments { get; set; }
        public string Timestamp { get; set; }

        public static PostIndexTableRow PostToRow(Blog.Post post, BlogDataDataContext database)
        {
            PostIndexTableRow row = new PostIndexTableRow();

            var commandButtonLeftHtml = "";
            commandButtonLeftHtml += "<a href='Post/ViewId?id=" + post.Id + "' class='btn btn-default hl-view' style='margin-right: 3px;'><i class='fa fa-search'></i></span></a>";
            commandButtonLeftHtml += "<a href='PostAdmin/Edit?id=" + post.Id + "' class='btn btn-default hl-view' style='margin-right: 3px;'><i class='fa fa-pencil'></i></span></a>";
            commandButtonLeftHtml += "<div class='btn btn-default hl-view deletePostButton' postId='" + post.Id + "'><i class='fa fa-trash'></i></div>";

            row.Id = commandButtonLeftHtml;
            row.Title = post.Title;
            row.Timestamp = post.Timestamp.ToString();

            
            var databaseAuthor = database.Users.FirstOrDefault(x => x.Id == post.Author);
            if (databaseAuthor != null)
            {
                row.Author = databaseAuthor.PublicName;
            }

            string tagsTemp = "";
            var databaseTagMaps = database.PostTagMaps.Where(x => x.PostId == post.Id);
            foreach (var tagMap in databaseTagMaps)
            {
                var databaseTag = database.PostTags.FirstOrDefault(x => x.Id == tagMap.TagId);
                tagsTemp += "<a href='" + "#" + "'>" + databaseTag.Name + "</a>, ";
            }
            row.Tags = tagsTemp; 
                      
            string categoriesTemp = "";
            var databaseCategoryMaps = database.PostCategoryMaps.Where(x => x.PostId == post.Id);
            foreach (var categoryMap in databaseCategoryMaps)
            {
                var databaseCategory = database.PostCategories.FirstOrDefault(x => x.Id == categoryMap.CategoryId);
                categoriesTemp += "<a href='" + "#" + "'>" + databaseCategory.Name + "</a>, ";
            }
            row.Categories = categoriesTemp;

            row.Comments = database.PostCommentMaps.Count(x => x.PostId == post.Id).ToString();          
 
            return row;
        }
    }


    // Page 1 is the most recent ten posts
    public class PostIndexTable
    {
        public List<PostIndexTableRow> Rows { get; set; }

        public static PostIndexTable GetTable(int page)
        {
            PostIndexTable table = new PostIndexTable();
            List<PostIndexTableRow> rows = new List<PostIndexTableRow>();

            using (BlogDataDataContext database = new BlogDataDataContext())
            {
                
                var posts = database.Posts.ToList().OrderByDescending(x => x.Timestamp).Skip((page - 1) * 10).Take(10);
                foreach (var post in posts)
                {
                    rows.Add(PostIndexTableRow.PostToRow(post, database));
                }
            }
            table.Rows = rows;

            return table;
        }
    }





    public class PostIndexTableResultModel
    {
        public int Draw { get; set; }
        public int RecordsTotal { get; set; }
        public int RecordsFiltered { get; set; }
        public List<PostIndexTableModel> Data { get; set; }

        public PostIndexTableResultModel(int draw, int recordsTotal, int recordsFiltered, List<PostIndexTableModel> data)
        {
            Draw = draw;
            RecordsTotal = recordsTotal;
            RecordsFiltered = recordsFiltered;
            Data = data;
        }
    }

    public class PostIndexTableModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Categories { get; set; }
        public string Tags { get; set; }
        public string Comments { get; set; }
        public string Timestamp { get; set; }

        public static PostIndexTableResultModel PostTable(HttpRequestBase Request)
        {
            string search = Request.Form.GetValues("search[value]")[0];
            string draw = Request.Form.GetValues("draw")[0];
            string order = Request.Form.GetValues("order[0][column]")[0];
            string orderDir = Request.Form.GetValues("order[0][dir]")[0];
            int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
            int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);

            List<PostIndexTableModel> postsTable = new List<PostIndexTableModel>();

            using (BlogDataDataContext database = new BlogDataDataContext())
            {
                var posts = database.Posts.ToList();

                foreach (var post in posts)
                {
                    postsTable.Add(FromPost(post, database));
                }
            }

            int totalRecords = postsTable.Count;

            if (!string.IsNullOrEmpty(search) && !string.IsNullOrWhiteSpace(search))
            {
                postsTable = postsTable.Where(x =>
                (x.Title != null ? x.Title.ToLower() : "").Contains(search.ToLower()) ||
                (x.Author != null ? x.Author.ToLower() : "").Contains(search.ToLower()) ||
                (x.Categories != null ? x.Categories.ToLower() : "").Contains(search.ToLower()) ||
                (x.Tags != null ? x.Tags.ToLower() : "").Contains(search.ToLower()) ||
                (x.Comments != null ? x.Comments.ToLower() : "").Contains(search.ToLower()) ||
                (x.Timestamp != null ? x.Timestamp.ToLower() : "").Contains(search.ToLower())
                ).ToList();
            }

            postsTable = SortByColumnWithOrder(order, orderDir, postsTable);

            int recFilter = postsTable.Count;
            postsTable = postsTable.Skip(startRec).Take(pageSize).ToList();

            return new PostIndexTableResultModel(Convert.ToInt32(draw), totalRecords, recFilter, postsTable);
        }

        public static PostIndexTableModel FromPost(Blog.Post post, BlogDataDataContext database)
        {
            var model = new PostIndexTableModel();

            var commandButtonLeftHtml = "";
            commandButtonLeftHtml += "<a href='Post/ViewId?id=" + post.Id.ToString() + "' class='btn btn-default hl-view' style='margin-right: 3px;'><i class='fa fa-search'></i></span></a>";
            commandButtonLeftHtml += "<a href='PostAdmin/Edit?id=" + post.Id.ToString() + "' class='btn btn-default hl-view' style='margin-right: 3px;'><i class='fa fa-pencil'></i></span></a>";
            commandButtonLeftHtml += "<div class='btn btn-default hl-view deletePostButton' postId='" + post.Id.ToString() + "'><i class='fa fa-trash'></i></div>";

            model.Id = commandButtonLeftHtml;
            model.Title = post.Title;
            model.Timestamp = post.Timestamp.ToString();

            /*
            var databaseAuthor = database.Users.FirstOrDefault(x => x.Id == post.Author);
            if (databaseAuthor != null)
            {
                model.Author = databaseAuthor.PublicName;
            }*/

            /*string tagsTemp = "";
            var databaseTagMaps = database.PostTagMaps.Where(x => x.PostId == post.Id);
            foreach (var tagMap in databaseTagMaps)
            {
                var databaseTag = database.PostTags.FirstOrDefault(x => x.Id == tagMap.TagId);
                tagsTemp += "<a href='" + "#" + "'>" + databaseTag.Name + "</a>, ";
            }
            model.Tags = tagsTemp; */
            /*            
            string categoriesTemp = "";
            var databaseCategoryMaps = database.PostCategoryMaps.Where(x => x.PostId == post.Id);
            foreach (var categoryMap in databaseCategoryMaps)
            {
                var databaseCategory = database.PostCategories.FirstOrDefault(x => x.Id == categoryMap.CategoryId);
                categoriesTemp += "<a href='" + "#" + "'>" + databaseCategory.Name + "</a>, ";
            }
            model.Categories = categoriesTemp;
            */

            //model.Comments = database.PostCommentMaps.Count(x => x.PostId == post.Id).ToString();

            return model;
        }

        public static List<PostIndexTableModel> SortByColumnWithOrder(string order, string orderDir,
            List<PostIndexTableModel> data)
        {
            List<PostIndexTableModel> list = new List<PostIndexTableModel>();

            try
            {
                switch (order)
                {
                    case "0":
                        list = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(x => x.Id).ToList() : data.OrderBy(x => x.Id).ToList();
                        break;
                    case "1":
                        list = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(x => x.Title).ToList() : data.OrderBy(x => x.Title).ToList();
                        break;
                    case "2":
                        list = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(x => x.Author).ToList() : data.OrderBy(x => x.Author).ToList();
                        break;
                    case "3":
                        list = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(x => x.Categories).ToList() : data.OrderBy(x => x.Categories).ToList();
                        break;
                    case "4":

Blog/Controllers/Admin/Post/PostAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models.Admin.Post;

namespace Blog.Controllers.Admin.Post
{
    public class PostAdminController : Controller
    {
        // GET: PostAdmin
        public ActionResult Posts(int? id)
        {
            PostIndexTable model = new PostIndexTable();
            if (id.HasValue)
            {
                model = Models.Admin.Post.PostIndexTable.GetTable(id.Value);
            }
            else
            {
                model = Models.Admin.Post.PostIndexTable.GetTable(1);
            }
            return View(model);
        }

        public ActionResult Edit(string id)
        {
            return View(PostEditModel.PostEdit(id));
        }

        [HttpPost]
        public JsonResult PostIndexTable()
        {
            var postTable = PostIndexTableModel.PostTable(Request);

            return Json(new
            {
                draw = postTable.Draw,
                recordsTotal = postTable.RecordsTotal,
                recordsFiltered = postTable.RecordsFiltered,
                data = postTable.Data
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditPost(PostEditModel model)
        {
            JsonResult jsonResult = new JsonResult();
            jsonResult.Data = PostEditModel.PostEditPost(model).Id;

            return jsonResult;
        }

        [HttpPost]
        public ActionResult DeletePostPost(string id)
        {
            JsonResult result = new JsonResult();
            result.Data = PostEditModel.DeletePost(id);
            return result;
        }
    }
}

Blog/Controllers/Post/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers.Post
{
    using Models.Post;
    public class PostController : Controller
    {
        // GET: Post
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewId(string id)
        {
            return View("View", PostViewModel.PostViewModelFromId(id));
        }

        public ActionResult View(string slug)
        {
            return View("View", PostViewModel.PostViewModelFromSlug(slug));
        }
    }
}

Blog/Views/PostAdmin/Edit.cshtml
@model Blog.Models.Admin.Post.PostEditModel

@{
    ViewBag.Title = Model.AddOrEdit + " Post";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <h2>@Model.AddOrEdit Post</h2>
            <br />
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <form id="Form" action="edit" method="post">
                <div class="col-md-9">
                    <div class="row">
                        <input type="text" class="form-control FullWidthTextInput" placeholder="Enter title here" value="@Model.Title" data-bind="value: Title"/>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-md-1">Permalink:</div>
                        <div class="col-md-10">
                            <input type="text" class="form-control" value="@Model.Slug" data-bind="value: Slug"/>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-md-12">
                            <textarea class="form-control" name="Body" id="Body" rows="10" cols="70" data-bind="value: Body">@Model.Body</textarea>                            
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-3">Status:</div>
                        <div class="col-md-9">
                            <select data-parsley-trigger="change" required="" class="form-control" data-bind="value: Status" value="@Model.Status">
                                @foreach (var possibleStatus in Model.PossibleStatuses)
                                {
                                    if (Model.Status == possibleStatus)
                                    {
                                        <option selected value="@possibleStatus">@possibleStatus</option>
                                    }
                                    else
                                    {
                                        <option value="@possibleStatus">@possibleStatus</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-md-3">Visibility:</div>
                        <div class="col-md-9">
                            <select data-parsley-trigger="change" required="" class="form-control" data-bind="value: Visibility" value="@Model.Visibility">
                                @foreach (var possibleVisibility in Model.PossibleVisibilities)
                                {
                                    if (Model.Visibility == possibleVisibility)
                                    {
                                        <option selected value="@possibleVisibility">@possibleVisibility</option>
                                    }
                                    else
                                    {
                                        <option value="@possibleVisibility">@possibleVisibility</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-md-3">Timestamp:</div>
                        <div class="col-md-9"><input type="text" id='datetimepicker4' class="form-control" value="@Model.Timestamp" data-bind="value: Timestamp"/>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-md-3">Comments:</div>
                            <div class="col-md-9">
                                <input type="checkbox" class="form-control" checked="@Model.CommentsEnabled" data-bind="checked: CommentsEnabled" />
                            </div>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <button type="button" data-bind="click: save" class="btn btn-success btn-md"><i class="fa fa-floppy-o"></i> Save</button>
                    </div>
                    <br/>
                    <div class="row">
                        Featured Image:
                    </div>
                    <div class="row">
                        <input type="text" class="form-control" value="@Model.FeaturedImage" data-bind="value: FeaturedImage" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">
    var initialModel = @Html.Raw(Json.Encode(Model));
    $(document).ready(function(){
        $('#datetimepicker4').datetimepicker();
    });
</script>
<script type="text/javascript" src="@Url.Content("~/Content/PostAdmin/PostEdit.js")"></script>

Blog/Views/PostAdmin/Index.cshtml
@{
    ViewBag.Title = "Posts";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <h2>Posts <a class="btn btn-success" href="@Url.Action("Edit", "PostAdmin")">Add</a></h2>
            <br />
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <table id="PostTable" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Categories</th>
                        <th>Tags</th>
                        <th>Comments</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        var userTable = $('#PostTable').DataTable({
            "processing": true,
            "serverSide": true,
            "order": [[6, "desc"]],
            "ajax": {
                "type": "POST",
                "url": "PostAdmin/PostIndexTable",
                "dataType": "JSON"
            },
            "processing": true,
            "paging": true,
            "deferRender": true,
            "columns": [
                {
                    "data": "Id",
                    sortable: false
                },
                { "data": "Title" },
                { "data": "Author" },
                {
                    "data": "Categories",
                    sortable: false
                },
                {
                    "data": "Tags",
                    sortable: false
                },
                { "data": "Comments" },
                { "data": "Timestamp" }
            ]
        });

        $("#PostTable").on("click", ".deletePostButton", function () {
            if (!confirm("Are you sure you want to permanently delete this post?")) return;
            var id = $(this).attr('postId');
            $.ajax({
                type: "POST",
                url: "./PostAdmin/DeletePostPost?id=" + id
            });
            $('#PostTable').DataTable().row($(this).parents('tr')).remove().draw();
        });
    });
</script>

Blog/Views/PostAdmin/Posts.cshtml
@model Blog.Models.Admin.Post.PostIndexTable

@{
    ViewBag.Title = "Posts";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <h2>Posts <a class="btn btn-success" href="@Url.Action("Edit", "PostAdmin")">Add</a></h2>
            <br />
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <table id="PostTable" class="display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Categories</th>
                    <th>Tags</th>
                    <th>Comments</th>
                    <th>Timestamp</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var row in Model.Rows)
                {
                    <tr>
                        <td>@Html.Raw(row.Id)</td>
                        <td>@Html.Raw(row.Title)</td>
                        <td>@Html.Raw(row.Author)</td>
                        <td>@Html.Raw(row.Categories)</td>
                        <td>@Html.Raw(row.Tags)</td>
                        <td>@Html.Raw(row.Comments)</td>
                        <td>@Html.Raw(row.Timestamp)</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

       /* var userTable = $('#PostTable').DataTable({
            "processing": true,
            "serverSide": true,
            "order": [[6, "desc"]],
            "ajax": {
                "type": "POST",
                "url": "PostAdmin/PostIndexTable",
                "dataType": "JSON"
            },
            "processing": true,
            "paging": true,
            "deferRender": true,
            "columns": [
                {
                    "data": "Id",
                    sortable: false
                },
                { "data": "Title" },
                { "data": "Author" },
                {
                    "data": "Categories",
                    sortable: false
                },
                {
                    "data": "Tags",
                    sortable: false
                },
                { "data": "Comments" },
                { "data": "Timestamp" }
            ]
        });

        $("#PostTable").on("click", ".deletePostButton", function () {
            if (!confirm("Are you sure you want to permanently delete this post?")) return;
            var id = $(this).attr('postId');
            $.ajax({
                type: "POST",
                url: "./PostAdmin/DeletePostPost?id=" + id
            });
            $('#PostTable').DataTable().row($(this).parents('tr')).remove().draw();
        }); */
    });
</script>