Blog/Controllers/Admin/User/UserAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models.Admin.User;

namespace Blog.Controllers.Admin.User
{
    public class UserAdminController : Controller
    {
        // GET: UserAdmin
        public ActionResult Index()
        {
            return View(UserIndexModel.UserIndex());
        }

        public ActionResult Edit(string id)
        {
            return View(UserEditModel.UserEdit(id));
        }

        [HttpPost]
        public ActionResult EditPost(UserEditModel model)
        {
            JsonResult jsonResult = new JsonResult();
            jsonResult.Data = UserEditModel.UserEditPost(model).Id;

            return jsonResult;
        }
    }
}

Blog/Views/UserAdmin/Edit.cshtml
@model Blog.Models.Admin.User.UserEditModel

@{
    ViewBag.Title = Model.AddOrEdit + " User";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <h2>@Model.AddOrEdit User</h2>
            <br />
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-4 col-md-offset-1">
            <form id="Form" action="edit" method="post">
                <table id="UserEditTable" class="table table-striped entryTable">
                    <tbody>
                        <tr>
                            <td><b>Username:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Username" data-bind="value: Username"/></td>
                        </tr>
                        <tr>
                            <td><b>Email:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Email" data-bind="value: Email"/></td>
                        </tr>
                        <tr>
                            <td><b>Role:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Role" data-bind="value: Role"/></td>
                        </tr>
                        <tr>
                            <td><b>First Name:</b></td>
                            <td><input type="text" class="form-control" value="@Model.FirstName" data-bind="value: FirstName"/></td>
                        </tr>
                        <tr>
                            <td><b>Last Name:</b></td>
                            <td><input type="text" class="form-control" value="@Model.LastName" data-bind="value: LastName"/></td>
                        </tr>
                        <tr>
                            <td><b>Nickname:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Nickname" data-bind="value: Nickname"/></td>
                        </tr>
                        <tr>
                            <td><b>Public Name:</b></td>
                            <td><input type="text" class="form-control" value="@Model.PublicName" data-bind="value: PublicName"/></td>
                        </tr>
                        <tr>
                            <td><b>Website:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Website" data-bind="value: Website"/></td>
                        </tr>
                        <tr>
                            <td><b>Biography:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Biography" data-bind="value: Biography"/></td>
                        </tr>
                        <tr>
                            <td><b>Profile Picture:</b></td>
                            <td><input type="text" class="form-control" value="@Model.ProfilePicture" data-bind="value: ProfilePicture"/></td>
                        </tr>
                        <tr>
                            <td><b>Password:</b></td>
                            <td><input type="text" class="form-control" value="@Model.Password" data-bind="value: Password" /></td>
                        </tr>
                        <tr>
                            <td style="padding-top: 30px">
                                <button type="button" data-bind="click: save" class="btn btn-success btn-md"><i class="fa fa-floppy-o"></i> Save</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">
    var initialModel = @Html.Raw(Json.Encode(Model));
    $(document).ready(function(){
    });
</script>
<script type="text/javascript" src="@Url.Content("~/Content/UserAdmin/UserEdit.js")"></script>

Blog/Views/UserAdmin/Index.cshtml
@model Blog.Models.Admin.User.UserIndexModel

@{
    ViewBag.Title = "Users";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <h2>Users <a class="btn btn-success" href="@Url.Action("Edit", "UserAdmin")">Add</a></h2>
            <br />
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-10 col-md-offset-1">
            <table id="UserTable" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>Username</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Posts</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Users)
            {
                        <tr>
                            <td>@user.Id</td>
                            <td>@user.Username</td>
                            <td>@user.FirstName @user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.Role</td>
                            <td>Todo</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var userTable = $('#UserTable').DataTable({
            "order": [[1, "asc"]],
            columns: [
                {
                    className: "commandButtonLeft",
                    data: "Id",
                    sortable: false,
                    render: function (data, type, full, meta) {
                        var commandButtonLeftHtml = "<a href='UserAdmin/Edit?id=" + data + "' class='btn btn-default hl-view' style='margin-right: 3px;'><i class='fa fa-pencil'></i></span></a>";
                        //commandButtonLeftHtml += "<a class='btn btn-default hl-view' data-toggle='modal' data-id='" + data + "' data-target='#deleteConfirmationModal'><i class='fa fa-trash'></i></span></a>";

                        return commandButtonLeftHtml;
                    },
                    width: "70"
                },
                { "data": "Username" },
                { "data": "Name" },
                { "data": "Email" },
                { "data": "Role" },
                { "data": "Posts" }
            ]
        });
    });
</script>